### ISSUE TITLE
Axon Endpoint 交接内容

### ISSUE THREAD

**Issue by ashuralyk** [synapseweb3/relayer#243]
## 测试文档

测试方式：在Axon测试链上部署IBC合约和2个mock client，然后用forcerelay的`start`命令进行测试，看是否能跑通。

Axon的测试需要准备环境，包括

- 测试网络。当前的Axon团队提供的地址为http://54.238.73.76:8000 ，这个地址上铺的是解除code size limit的版本。
- 在测试网络上部署合约。包括：部署IBC合约、注册两个Client。
- 配置Forcerelay。配置文件位于`~/.hermes`下

## 合约准备

在项目ibc-solidity-contract的根目录下

1. 向`.env`文件中添加`AXON_RPC_URL=http://54.238.73.76:8000/`
2. 运行两次 `npx truffle migrate --network axon` 以部署两个独立的 IBCHandler 合约

部署所用的账户位于`truffle-config.js`中的`axon.provider`下。目前使用的是助记词`test test test test test test test test test test test junk`，可根据情况修改。

## forcerelay配置

在`~/.hermes/config.toml`中添加下面的配置

```toml
[[chains]]
id = 'axon-0'
websocket_addr = "ws://54.238.73.76:8010"
rpc_addr = "http://54.238.73.76:8000/"
contract_address = "<your_ibc_handler_address_1>"
key_name = "relayer_axon_wallet"
store_prefix = "axon_store_prefix"
ckb_light_client_contract_address = "0x71C7656EC7ab88b098defB751B7401B5f6d8976F"
image_cell_contract_address = "0x71C7656EC7ab88b098defB751B7401B5f6d8976F"

[[chains]]
id = 'axon-1'
websocket_addr = "ws://54.238.73.76:8010"
rpc_addr = "http://54.238.73.76:8000/"
contract_address = "<your_ibc_handler_address_2>"
key_name = "relayer_axon_wallet"
store_prefix = "axon_store_prefix"
ckb_light_client_contract_address = "0x71C7656EC7ab88b098defB751B7401B5f6d8976F"
image_cell_contract_address = "0x71C7656EC7ab88b098defB751B7401B5f6d8976F"
```

接着在forcerelay目录下，执行命令`forcerelay keys add --key-file crates/relayer/tests/config/fixtures/relayer-seed.json --chain axon-0`和`forcerelay keys add --key-file crates/relayer/tests/config/fixtures/relayer-seed.json --chain axon-1`。

### Forcerelay 主动发起命令测试
执行 `Forcerelay create connection --a-chain axon-0 --b-chain axon-1` 在 Axon 上的两个 Handler 合约中建立 connection 连接。

之后，再执行 `Forcerelay create channel --a-chain axon-0 --a-connection connection-0 --a-port mock-port-0 --b-port mock-port-0` 在之前创建的 connection 上建立 channel 连接。

### Forcerelay 监听模式测试
执行`forcerelay start`，进入监听。

我们需要手动发OpenInit交易，才能触发IBC事件。下面是一个例子：

```js
const clientId = "AxonClient-0";
const counterpartyClientId = "AxonClient-0";
const counterpartyPrefix = ethers.utils.toUtf8Bytes("axon_store_prefix");
const msgConnectionOpenInit = {
  clientId: clientId,
  counterparty: {
    clientId: counterpartyClientId,
    connectionId: "",
    prefix: {
      keyPrefix: counterpartyPrefix,
    },
  },
  delayPeriod: 0,
};
let connectionAttr = await ibcHandler.connectionOpenInit.call(msgConnectionOpenInit);
console.log(connectionAttr);
const tx = await ibcHandler.connectionOpenInit(msgConnectionOpenInit);
console.log(tx);
```

将这段逻辑替换掉`ibc-solidity-contract`中的`1_deploy_contracts.js`文件中的主逻辑，然后执行`npx truffle migrate --network axon`，就能发送IBC交易。
